INSERT INTO EMPLOYEES (IDNUMBER, 
                       LASTNAME,
                       FIRSTNAME,
                       MIDDLENAME,
                       HOMEADDRESS,
                       PHONE,
                       PASS_WORD, 
                       ACTIVESERVICE,
                       SIGNATURE, 
                       PICTURE, 
                       POSITIONRANK,
                       GENDER)
               VALUES ('10001', 
                       'ALMORADO',
                       'Roland', 
                       'Cinco',
                       'Alicia, Zamboanga Sibugay',
                       '09085284459',
                       'JPJULIA.LJ',
                       '1',
                       NULL,
                       '[BINARY]', 
                       'Instructor I',
                       'Male');


INSERT INTO EMPLOYEES (IDNUMBER, 
                       LASTNAME,
                       FIRSTNAME,
                       MIDDLENAME,
                       HOMEADDRESS,
                       PHONE,
                       PASS_WORD, 
                       ACTIVESERVICE,
                       SIGNATURE, 
                       PICTURE, 
                       POSITIONRANK,
                       GENDER)
               VALUES ('10010', 
                       'ANUB',
                       'Remedios',
                       'Rapirap',
                       'Alicia, Zamboanga Sibugay',
                       '09085284459',
                       'remrem',
                       '1',
                       NULL,
                       '[BINARY]', 
                       'Instructor 2',
                       'Female');


INSERT INTO EMPLOYEES (IDNUMBER, 
                       LASTNAME,
                       FIRSTNAME,
                       MIDDLENAME,
                       HOMEADDRESS,
                       PHONE,
                       PASS_WORD, 
                       ACTIVESERVICE,
                       SIGNATURE, 
                       PICTURE, 
                       POSITIONRANK,
                       GENDER)
               VALUES ('10003', 
                       'BADINAS',
                       'Mariano',
                       'Rapirap',
                       'Alicia, Zamboanga Sibugay',
                       '',
                       '1234',
                       '1',
                       NULL,
                       '[BINARY]', 
                       'Associate Professor 5',
                       'Female');
